fix: can't start USE in IDE
When starting USE in IntelliJ the following error occurred:

java.lang.module.FindException: Module lombok not found, required by use.gui

Since lombok is only used during compile time, the module dependency definition was set to static.